apiVersion: v1
kind: Service
metadata:
  name: external-name-mysql
  namespace: fullstack-app
spec:
  type: ExternalName
  externalName: 'backend-service.fullstack-app.svc.cluster.local'
  # will get the value in service "backend-service"
  # which in the service part of  backend-deployment.yaml

