apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-be-app
  namespace: task3-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice-be-app
  template:
    metadata:
      labels:
        app: webservice-be-app
    spec:
      imagePullSecrets:
        - name: lesson3-secret # add below the AWS secret created before
      containers:
      - name: webservice-be-app # this is the backend app
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        image: 148761662110.dkr.ecr.us-east-1.amazonaws.com/cloudarchitecture/l3-worker-service-backend:1.0
        env:
        - name: AWS_ID
          valueFrom:
            secretKeyRef:
              name: aws-id-secret
              key: AWS_ID
        - name: WEB_SERVICE_NAME
          value: web-app-fe-service.task3-namespace.svc.cluster.local
        ports:
        - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: webservice-be-app-service
  namespace: task3-namespace
spec:
  selector:
    app: webservice-be-app # Match with Deployment labels.
  ports:
    - protocol: TCP
      name: webservice-app-service
      port: 5002
      targetPort: 5002
  type: ClusterIP