apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: summaryexperts/flask-app:latest
        volumeMounts:
        - mountPath: "/data"
          name: my-storage
        ports:
        - containerPort: 5000
      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: my-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort