apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-application.fullname" . }}
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}