apiVersion: v1
kind: Pod
metadata:
  name: psql-client
spec:
  containers:
  - name: psql-client
    image: postgres:latest
    command: ['sh', '-c', 'while true; do sleep 3600; done']
  restartPolicy: Never