apiVersion: v1
kind: Service
metadata:
  name: external-name-redis
  namespace: multi-tier-app
spec:
  type: ExternalName
  externalName: 'python-backend-app.multi-tier-app.svc.cluster.local'
  # will get the value in service "python-backend-app"
  # which in the service part of the service in backend-deployment.yaml

