services:
  flask:
    build: .
    container_name: my-flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - redis

  redis:
    image: redis:7.2.4
    container_name: my-redis-service
    ports:
      - "6379:6379"
