apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: secure-app
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded password (e.g., 'password')
  MONGO_INITDB_ROOT_USERNAME: YWRtaW51c2Vy #adminuser
