apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: pods-services-cluster-role
rules:
- apiGroups: [""]
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "pods" and "services"
  resources: [ "pods", "services" ]
  verbs: [ "create", "get", "list", "watch", "update", "delete" ]
