apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: multi-tier-app
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"