apiVersion: v1
kind: Service
metadata:
  name: external-name-mysql
  namespace: secure-app
spec:
  type: ExternalName
  externalName: 'python-backend-service.secure-app.svc.cluster.local'
  # will get the value in service "python-backend-service"
  # which in the service part of the service in mongodb-backend.yaml

