apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend-app
  namespace: multi-tier-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-backend-app
  template:
    metadata:
      labels:
        app: python-backend-app
    spec:
      containers:
      - name: python-backend-app
        image: yidgar11/redis-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config # Reference your ConfigMap.
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config # Reference your ConfigMap.
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret # Reference your secret.
              key: REDIS_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: python-backend-service # The stable DNS name
  namespace: multi-tier-app
spec:
  selector:
    app: python-backend-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
