apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: fullstack-app
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        resources:
          requests:
            memory: "200Mi"
            cpu: "1"
          limits:
            memory: "500Mi"
            cpu: "2"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fullstack-app
spec:
  ports:
  - port: 3306
  selector:
    app: mysql